include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

variables:
  DISABLE_BLACK_FLAKE8: "yes"

# test-3.10:
#   extends: .test-3.10

# test-3.14:
#   extends: .test-3.14

# build_sdist:
#   extends: .build_sdist

# test_sdist-3.10:
#   extends: .test_sdist-3.10

# test_sdist-3.14:
#   extends: .test_sdist-3.14

ruff:
  extends: .ruff

build_doc:
  extends: .build_doc

pages:
  extends: .pages

assets:
  extends: .assets

pypi:
  extends: .pypi

testpypi:
  extends: .testpypi
